---
version: "3.8"

services:

  admin:
    depends_on:
      - mssql
    env_file:
      - global-settings.env
    image: bitwarden/admin:${CORE_TAG:-latest}
    restart: always
    volumes:
      - attachments:/etc/bitwarden/core/attachments
      - aspnet-dataprotection:/etc/bitwarden/core/aspnet-dataprotection
      - logs-admin:/etc/bitwarden/logs/Admin

  api:
    env_file:
      - global-settings.env
    image: bitwarden/api:${CORE_TAG:-latest}
    restart: always
    volumes:
      - attachments:/etc/bitwarden/core/attachments
      - aspnet-dataprotection:/etc/bitwarden/core/aspnet-dataprotection
      - logs-api:/etc/bitwarden/logs/Api

  attachments:
    env_file:
      - global-settings.env
    image: bitwarden/attachments:${CORE_TAG:-latest}
    restart: always
    volumes:
      - attachments:/etc/bitwarden/core/attachments

  events:
    env_file:
      - global-settings.env
    image: bitwarden/events:${CORE_TAG:-latest}
    restart: always
    volumes:
      - logs-events:/etc/bitwarden/logs/Events
        
  icons:
    env_file:
      - global-settings.env
    image: bitwarden/icons:${CORE_TAG:-latest}
    restart: always
    volumes:
      - logs-icons:/etc/bitwarden/logs/Icons

  identity:
    env_file:
      - global-settings.env
    image: bitwarden/identity:${CORE_TAG:-latest}
    restart: always
    volumes:
      - attachments:/etc/bitwarden/core/attachments
      - aspnet-dataprotection:/etc/bitwarden/core/aspnet-dataprotection
      - identity:/etc/bitwarden/identity
      - logs-identity:/etc/bitwarden/logs/Identity
      
  mssql:
    env_file:
      - global-settings.env
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    image: mcr.microsoft.com/mssql/server:2017-CU18-ubuntu-16.04
    restart: always
    volumes:
      - mssql_data:/var/opt/mssql/data
      - mssql_logs:/var/opt/mssql/log
        
  nginx:
    depends_on:
      - admin
      - api
      - identity
      - web
    env_file:
      - global-settings.env
    environment:
      BW_ENABLE_SSL: "true"
    image: bitwarden/nginx:${CORE_TAG:-latest}
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ssl:/etc/bitwarden/ssl

  notifications:
    env_file:
      - global-settings.env
    image: bitwarden/notifications:${CORE_TAG:-latest}
    restart: always
    volumes:
      - logs-notifications:/etc/bitwarden/logs/Notifications

  sso:
    env_file:
      - global-settings.env
    image: bitwarden/sso:${CORE_TAG:-latest}
    restart: always
    volumes:
      - attachments:/etc/bitwarden/core/attachments
      - aspnet-dataprotection:/etc/bitwarden/core/aspnet-dataprotection
      - identity:/etc/bitwarden/identity
      - logs-sso:/etc/bitwarden/logs/SSO
        
  web:
    env_file:
      - global-settings.env
    image: bitwarden/web:${WEB_TAG:-latest}
    restart: always
    volumes:
      - web:/etc/bitwarden/web

volumes:
  attachments:
  aspnet-dataprotection:
  identity:
  logs-admin:
  logs-api:
  logs-events:
  logs-icons:
  logs-identity:
  logs-notifications:
  logs-sso:
  mssql_data:
  mssql_logs:
  ssl:
  web:
